[build]
builder = "NIXPACKS"
buildCommand = "pnpm install --no-frozen-lockfile && pnpm run build"

[deploy]
startCommand = "pnpm start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[deploy.pre]]
cmd = "pnpm run db:push"
